version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cxchat
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
